language: php
php:
  - 5.6
cache:
  directories:
    - node_modules
    - vendor
install:
  - composer install
before_script:
  - npm install -g bower
  - bower install
  - cp .env.travis .env
  - mysql -e 'create database AValcohol;'
  - php artisan migrate:install --env=testing --no-interaction -vvv
script:
  - php artisan migrate --env=testing --no-interaction -vvv
  - php artisan db:seed --env=testing --no-interaction -vvv
  - phpunit
notifications:
  email: false
services:
  - mysql
env:
  global:
    - secure: hSbIGLsXEVCfE9MwxdEToJnkBLJEOVVk5vEbX1BUd56wKgjQSokB1S2vAn5QNtxLFxFBv1j4ez3+Hyuu9mfAjmIWLINwlr81C7yV2Ol4mUdido20upFUSxedYeeAEl73EtODAGsAxWxRQNHFk7PzOro3CJtfEWfm8PrY9SmRxTg/6HjhdT4RmzpuQ0rEV3putUHDRFn2jiK7LcgpX3S0tI0rhhG/xi4h5MJNGYQ7ZLHXh4m5wJcKG8FnvoVKE67/7MqZAiA0QYKTIK9Z6GikaI4IXopiyASi4IZ6igueelg1IusjwQsCLwAgOP1j1dCRJMff9XaYxMZoEWiQ0ZllP2q+KI+Sx5L33W8DJRQGIRmUeWX1809/Ey4xt2Bl8MtEiYPt0DHS2CkNPOYaxF3Q4FY2w7CQIqNqqxhZnmLuAJv1dJIuORJ+0UzTe9le3evYFpL35cE4Ll30SLDv9hnDh0jhaJnwPYVJqnkqpi6yrmkf56uw20XRJR1q7tKE8OkTdgZRfbdSz/AS4gcLYqnkEckf43dWn+pnTLKG2oaXroJQ4OwaH2apd0z2alXGPo4FbhnJI7V0VPvAGa7R/6f5OCuZLNA4DzBWFRIY3FiPQ9NqXl57rxOqzJMpARGCe+BEmFIu9jSxdKD+sjMka1oFK0m0gkaSRVgox/v4VW1ivDk=
    - secure: BSR9sdpBFxSF8hQHQ52dmS93rLF6UMxu5bFi2Xk1VpM4L1yJ3oPVQtwayl3Wwb/X4Xn/uVfdSzogT848oNfHzn6iy2diz032lkP6JefAzUtINvRgAQCZxlkgr0O2jhApBFIncXEOSZFxNxoA+6fPgtS63m1N2oPohctYOI3aecLvCISmvOnNe9WHcxDOwZWK7pWqg/3XClA6b+iZZ4FkBFsAVRLHDwV0LXDMXSKTV90NhdqfIUwzWUfiod5IEkGxBxbpdh/YKiLHeEok0YWHrlaGuoeZfxC4RCq3wS66UdInDS0bBgu1+b4sBndRRyG2VfZ53ci1yK1KIHSrYFJlW7fZNerK2ciAzCEG87T715tSmRn30aqd49MG3jAHxv9gLGiHnHL/xXCvRprEeS4ep9z1peoYTxofGV3AsIywedsZVr9qr4UZor3YalVpT/ekYA3yDfZKIre+SvetvFo4Nn29wZRZJJr/DZxFpTRzUErXxBhMclqXjkNfZ8ZfltLRsuQ/GtbTckA4toTrYBqbU+2w54jC08cqIlv/BjwDH/Y09L1wjQPtG+1wyiW5aK3Bw6O4peahx5Y9NRiGjacdnkE7eyszxvLTwvlUuS/ca5SJ2BeAa5QKNVYmddjLiJRiHeeMr7q8sW6zXqBtht2CzxsMMbnKPCHc4cUHATA/tNw=
after_success:
  - bash ./deploy.sh