language: php
php:
  - 5.6
install:
  - composer install
before_script:
  - npm install -g bower
  - bower install
  - cp .env.travis .env
  - mysql -e 'create database AValcohol;'
  - php artisan migrate:install --env=testing --no-interaction -vvv
script:
  - php artisan migrate --env=testing --no-interaction -vvv
  - php artisan db:seed --env=testing --no-interaction -vvv
  - phpunit
notifications:
  email: false
services:
  - mysql