language: php
php:
  - 5.6
install:
  - composer install
before_script:
  - npm install -g bower
  - bower install
  - cp .env.travis .env
  - mysql -e 'create database AValcohol;'
  - php artisan migrate:install --no-interaction -vvv
notifications:
  email: false
services:
  - mysql